(function(root){
  'use strict';
  class AudioService{
    constructor(){this.ctx=null;this.master=null;this.musicGain=null;this.sfxGain=null;this.musicTimer=null;this.musicStep=0;this.enabled=true;}
    ensure(){if(this.ctx)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.musicGain=this.ctx.createGain();this.sfxGain=this.ctx.createGain();this.musicGain.connect(this.master);this.sfxGain.connect(this.master);this.master.connect(this.ctx.destination);}
    resume(){this.ensure();if(this.ctx?.state==='suspended')this.ctx.resume();}
    setVolumes(settings){this.ensure();if(!this.ctx)return;this.master.gain.value=.75;this.musicGain.gain.value=settings.music??.5;this.sfxGain.gain.value=settings.sfx??.7;}
    tone(freq=440,duration=.09,type='square',volume=.12,slide=0){this.ensure();if(!this.ctx||!this.enabled)return;const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+duration);g.gain.setValueAtTime(0.0001,now);g.gain.exponentialRampToValueAtTime(volume,now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(this.sfxGain);o.start(now);o.stop(now+duration+.02);}
    noise(duration=.12,volume=.1){this.ensure();if(!this.ctx)return;const length=Math.floor(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,length,this.ctx.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<length;i++)d[i]=(Math.random()*2-1)*(1-i/length);const src=this.ctx.createBufferSource(),g=this.ctx.createGain();g.gain.value=volume;src.buffer=buffer;src.connect(g);g.connect(this.sfxGain);src.start();}
    sfx(name){const map={jump:[380,.09,'square',.12,220],shoot:[720,.055,'square',.08,-260],hit:[120,.12,'sawtooth',.14,-60],collect:[880,.08,'square',.08,180],checkpoint:[440,.35,'triangle',.13,440],dash:[220,.12,'sawtooth',.11,620],boss:[90,.45,'sawtooth',.14,40],ui:[600,.045,'square',.055,100],grade:[520,.35,'triangle',.12,520],hurt:[160,.2,'square',.12,-80]};const a=map[name]||map.ui;this.tone(...a);if(name==='hit'||name==='dash')this.noise(.08,.035);}
    startMusic(mode='menu'){this.stopMusic();this.ensure();if(!this.ctx)return;const scales={menu:[220,277,330,440,330,277],game:[196,247,294,392,294,247,220,294],boss:[110,131,147,165,147,131],hospital:[262,330,392,523,392,330],endless:[174,220,261,349,261,220]};const notes=scales[mode]||scales.game;const bpm=mode==='boss'?150:mode==='endless'?140:105;this.musicStep=0;const tick=()=>{if(!this.ctx)return;const f=notes[this.musicStep++%notes.length];const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=mode==='hospital'?'sine':'square';o.frequency.value=f;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.035,now+.02);g.gain.exponentialRampToValueAtTime(.0001,now+.18);o.connect(g);g.connect(this.musicGain);o.start(now);o.stop(now+.2);if(this.musicStep%4===0){const b=this.ctx.createOscillator(),bg=this.ctx.createGain();b.type='triangle';b.frequency.value=f/2;bg.gain.setValueAtTime(.025,now);bg.gain.exponentialRampToValueAtTime(.0001,now+.28);b.connect(bg);bg.connect(this.musicGain);b.start(now);b.stop(now+.3);}};tick();this.musicTimer=setInterval(tick,60000/bpm/2);}
    stopMusic(){if(this.musicTimer){clearInterval(this.musicTimer);this.musicTimer=null;}}
  }
  root.LLAudio=new AudioService();
})(window);
