(function(){
'use strict';
const D=window.LastLessonData,L=window.LLLogic,S=window.LLSave,A=window.LLAudio,Services=window.LLServices;
const screen=document.getElementById('screen'),topbar=document.getElementById('topbar'),gameLayer=document.getElementById('gameLayer'),modalRoot=document.getElementById('modalRoot');
const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
let save=S.load(), currentScreen='main', engine=null, raf=0, lastTime=0;
const refs={profileName:document.getElementById('profileName'),profileAvatar:document.getElementById('profileAvatar'),books:document.getElementById('booksValue'),gum:document.getElementById('gumValue'),online:document.getElementById('onlineStatus'),hearts:document.getElementById('heartHud'),runBooks:document.getElementById('runBooks'),runGum:document.getElementById('runGum'),runDoodles:document.getElementById('runDoodles'),bossHud:document.getElementById('bossHud'),bossName:document.getElementById('bossName'),bossBar:document.getElementById('bossBar'),toast:document.getElementById('toast')};
const input={left:false,right:false,down:false,jump:false,jumpPressed:false,attack:false,attackPressed:false,sprint:false,dash:false,dashPressed:false,interact:false,interactPressed:false};

function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(n){return Math.floor(n||0).toLocaleString('de-DE');}
function saveNow(){S.save(save);updateTopbar();}
function updateTopbar(){refs.profileName.textContent=save.profile.name||'Spieler';refs.profileAvatar.textContent=save.profile.presentation==='female'?'👧':save.profile.presentation==='male'?'👦':'🙂';refs.books.textContent=fmt(save.wallet.books);refs.gum.textContent=fmt(save.wallet.gum);}
function setTopbar(show){topbar.classList.toggle('hidden',!show);}
function stopGame(){if(raf)cancelAnimationFrame(raf);raf=0;engine=null;gameLayer.classList.add('hidden');refs.bossHud.classList.add('hidden');resetInput();}
function resetInput(){Object.keys(input).forEach(k=>input[k]=false);}
function navigate(name,payload){stopGame();currentScreen=name;setTopbar(!['main','character'].includes(name));screen.className='screen';screen.scrollTop=0;A.resume();A.setVolumes(save.settings);A.startMusic(name==='hospital'?'hospital':'menu');const routes={main:renderMain,character:renderCharacter,play:renderPlay,story:renderStory,shop:renderShop,report:renderReport,skills:renderSkills,pocket:renderPocket,settings:renderSettings,training:()=>startGame({mode:'training',chapter:0,level:0}),endless:()=>startGame({mode:'endless',chapter:0,level:0})};(routes[name]||renderMain)(payload);updateTopbar();}
function header(title,back='main',subtitle=''){return `<div class="page-head"><div><h1>${esc(title)}</h1>${subtitle?`<p class="muted">${esc(subtitle)}</p>`:''}</div><button class="back" data-nav="${back}">← Zurück</button></div>`;}
function bindNav(){screen.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{A.sfx('ui');navigate(b.dataset.nav);}));}
function showModal(html){modalRoot.innerHTML=`<div class="modal">${html}</div>`;modalRoot.classList.remove('hidden');}
function closeModal(){modalRoot.classList.add('hidden');modalRoot.innerHTML='';}
function toast(text,ms=1800){refs.toast.textContent=text;refs.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>refs.toast.classList.add('hidden'),ms);}

function renderMain(){
 setTopbar(false);screen.className='screen center';
 screen.innerHTML=`<section class="hero"><p class="pill">Browser Edition · HTML/CSS/JS</p><h1 class="title">Last Lesson<br>Final Period</h1><p class="subtitle">Der Regelreaktor hat den Schultag außer Kontrolle gebracht. Kämpfe dich durch acht Kapitel, sammle Kritzeleien und erreiche den Schulschluss.</p><div class="menu-grid"><button class="menu-button" data-main="play">Spielen</button><button class="menu-button" data-main="shop">Shop</button><button class="menu-button" data-main="report">Zeugnis</button><button class="menu-button" data-main="skills">Fähigkeiten</button><button class="menu-button" data-main="pocket">Hosentasche</button><button class="menu-button" data-main="settings">Einstellungen</button></div><p class="muted" style="margin-top:18px">Tastatur: A/D · Space · Shift · J · K · E · Esc. Touch-Steuerung erscheint im Level.</p></section>`;
 screen.querySelectorAll('[data-main]').forEach(b=>b.addEventListener('click',()=>{A.sfx('ui');const t=b.dataset.main;if(t==='play'&&!save.profileCreated)navigate('character');else navigate(t);}));
}

function avatarMarkup(){return `<div class="avatar-pixel" style="--skin:${save.profile.skin};--hair:${save.profile.hair};--shirt:${save.profile.shirt};--pants:${save.profile.pants}"><span class="avatar-hair"></span><span class="avatar-head"></span><span class="avatar-body"></span><span class="avatar-leg a"></span><span class="avatar-leg b"></span></div>`;}
function renderCharacter(){
 setTopbar(false);screen.innerHTML=`<div class="page">${header('Charaktererstellung','main','Keine Schultasche: Schultaschen werden ausschließlich erspielt.')}<div class="grid-2"><div class="panel form-grid"><div class="field" style="grid-column:1/-1"><label for="charName">Name</label><input id="charName" maxlength="16" value="${esc(save.profile.name)}" autocomplete="off"><small class="muted">2–16 Zeichen, keine Kontaktangaben oder URLs.</small></div><div class="field"><label>Darstellung</label><select id="presentation"><option value="neutral">Neutral</option><option value="female">Weiblich</option><option value="male">Männlich</option></select></div><div></div><div class="field" style="grid-column:1/-1"><label>Hautton</label><div class="swatches" data-color="skin">${['#f0c6a4','#d9a37b','#bd7e56','#9b6042','#77452f','#543224'].map(c=>`<button class="swatch" style="background:${c}" data-value="${c}"></button>`).join('')}</div></div><div class="field" style="grid-column:1/-1"><label>Haarfarbe</label><div class="swatches" data-color="hair">${['#171717','#3e2c24','#795239','#c89f57','#a64c42','#784b88','#c14d78'].map(c=>`<button class="swatch" style="background:${c}" data-value="${c}"></button>`).join('')}</div></div><div class="field" style="grid-column:1/-1"><label>Oberteil</label><div class="swatches" data-color="shirt">${['#c1475b','#3d74a8','#4e8a60','#c58c32'].map(c=>`<button class="swatch" style="background:${c}" data-value="${c}"></button>`).join('')}</div></div><div class="field" style="grid-column:1/-1"><label>Hose</label><div class="swatches" data-color="pants">${['#263a60','#22242b','#53604a','#6c4f42'].map(c=>`<button class="swatch" style="background:${c}" data-value="${c}"></button>`).join('')}</div></div><button id="createCharacter" class="primary" style="grid-column:1/-1">Schultag beginnen</button></div><div class="avatar-preview" id="avatarPreview">${avatarMarkup()}</div></div></div>`;
 document.getElementById('presentation').value=save.profile.presentation;
 document.querySelectorAll('[data-color]').forEach(group=>group.querySelectorAll('.swatch').forEach(btn=>{if(btn.dataset.value===save.profile[group.dataset.color])btn.classList.add('active');btn.addEventListener('click',()=>{save.profile[group.dataset.color]=btn.dataset.value;group.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x===btn));document.getElementById('avatarPreview').innerHTML=avatarMarkup();A.sfx('ui');});}));
 document.getElementById('createCharacter').addEventListener('click',()=>{const name=document.getElementById('charName').value.trim();if(!validName(name)){showModal(`<h2>Name nicht möglich</h2><p>Bitte 2–16 Zeichen ohne URL, E-Mail-Adresse oder Telefonnummer eingeben.</p><div class="modal-actions"><button class="primary" id="okModal">Verstanden</button></div>`);document.getElementById('okModal').onclick=closeModal;return;}save.profile.name=name;save.profile.presentation=document.getElementById('presentation').value;save.profileCreated=true;saveNow();navigate('play');});bindNav();
}
function validName(n){return n.length>=2&&n.length<=16&&!/https?:|www\.|@|\d{6,}/i.test(n)&&!/fuck|shit|nazi|hurensohn/i.test(n);}

function renderPlay(){screen.innerHTML=`<div class="page">${header('Spielen','main')}<div class="grid-3"><button class="panel card-button" data-nav="story"><h2>Story-Modus</h2><p>Acht Kapitel, 32 Level, Bosse und Sammelobjekte.</p></button><button class="panel card-button" data-nav="endless"><h2>Dauernachsitzen</h2><p>Endloslauf mit einem Herz und standardisierten Werten.</p></button><button class="panel card-button" id="phoneMini"><h2>Handy-Minispiel</h2><p>Grobes Retro-Jump-and-Run aus dem Schulbus.</p></button><button class="panel card-button" data-nav="training"><h2>Pausenhof-Training</h2><p>Fähigkeiten ohne Kosten testen.</p></button></div></div>`;bindNav();document.getElementById('phoneMini').onclick=()=>startGame({mode:'phone',chapter:0,level:2});}

function renderStory(){
 const unlocked=save.story.unlocked;screen.innerHTML=`<div class="page">${header('Story-Modus','play','Die Karte deckt sich mit dem Fortschritt auf.')}<div class="chapter-list">${D.chapters.map((ch,ci)=>`<section class="chapter" style="--chapter:${ch.color}"><div class="chapter-head"><div><b>Kapitel ${ch.id}</b><h2>${esc(ch.title)}</h2></div><span>${ci*4+1<=unlocked?'Verfügbar':'Gesperrt'}</span></div><div class="chapter-levels">${ch.levels.map((lv,li)=>{const g=ci*4+li+1,locked=g>unlocked,st=save.story.levelStats[`${ci+1}-${li+1}`]||{};return `<button class="level-card ${li===3?'boss':''} ${locked?'locked':''}" data-level="${ci},${li}" ${locked?'disabled':''}><span class="number">${ch.id}.${li+1}</span><span class="grade">${st.grade||'–'}</span><h3>${esc(lv[0])}</h3><small>Bestzeit: ${st.bestTime?formatTime(st.bestTime):'–'} · Kritzeleien ${st.doodles||0}/3</small>${lv[2]?`<small class="warn">Fund/Freischaltung: ${esc(lv[2])}</small>`:''}</button>`;}).join('')}</div></section>`).join('')}</div></div>`;
 bindNav();screen.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{const [chapter,level]=b.dataset.level.split(',').map(Number);startGame({mode:'story',chapter,level});}));
}

function renderSkills(){
 const categories=['Bewegung','Kampf','Überleben','Sammeln','Prüfungen'];let active='Bewegung';
 const draw=()=>{screen.innerHTML=`<div class="page">${header('Fähigkeiten','main',`Verfügbare Fähigkeitspunkte: ${save.wallet.abilityPoints}`)}<div class="tabs">${categories.map(c=>`<button class="tab ${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><div class="item-grid">${(active==='Prüfungen'?D.abilities:D.abilities.filter(a=>a.category===active)).map(a=>skillCard(a,active==='Prüfungen')).join('')}</div></div>`;bindNav();screen.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{active=b.dataset.cat;draw();});screen.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>upgradeAbility(b.dataset.upgrade));screen.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>startGame({mode:'training',chapter:0,level:0,focus:b.dataset.test}));};draw();
}
function skillUnlocked(a){return save.story.unlocked>a.unlock||a.unlock===0;}
function skillCard(a,tests){const unlocked=skillUnlocked(a),level=save.abilities[a.id]||0,cost=a.cost[Math.min(level,a.cost.length-1)];return `<article class="item-card ${unlocked?'':'disabled'}"><div class="row spread"><span class="item-icon">${a.icon}</span><span class="pill">Stufe ${level}/${a.max}</span></div><h3>${a.name}</h3><p class="${unlocked?'':'locked-text'}">${a.desc}</p>${tests?`<p class="muted">Prüfungen: Lernprüfung · Kombination · Meisterprüfung</p><button class="secondary" data-test="${a.id}" ${unlocked?'':'disabled'}>Testen</button>`:`<div class="row"><button class="secondary" data-test="${a.id}" ${unlocked?'':'disabled'}>Testen</button><button class="primary" data-upgrade="${a.id}" ${!unlocked||level>=a.max||save.wallet.abilityPoints<cost?'disabled':''}>Verbessern (${cost} AP)</button></div>`}</article>`;}
function upgradeAbility(id){const a=D.abilities.find(x=>x.id===id),level=save.abilities[id]||0;if(!a||level>=a.max)return;const cost=a.cost[level];if(save.wallet.abilityPoints<cost)return;save.wallet.abilityPoints-=cost;save.abilities[id]=level+1;saveNow();A.sfx('grade');renderSkills();}

function renderPocket(){
 let tab='weapons';const draw=()=>{screen.innerHTML=`<div class="page">${header('Hosentasche','main')}<div class="tabs"><button class="tab ${tab==='weapons'?'active':''}" data-tab="weapons">Waffen</button><button class="tab ${tab==='cosmetics'?'active':''}" data-tab="cosmetics">Kleidung & Skins</button><button class="tab ${tab==='items'?'active':''}" data-tab="items">Gefundene Gegenstände</button><button class="tab ${tab==='collection'?'active':''}" data-tab="collection">Sammlung</button></div><div id="pocketBody">${pocketBody(tab)}</div></div>`;bindNav();screen.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;draw();});screen.querySelectorAll('[data-equip-weapon]').forEach(b=>b.onclick=()=>{save.weapons.main=b.dataset.equipWeapon;saveNow();draw();});screen.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>rangeUpgrade(b.dataset.range));screen.querySelectorAll('[data-equip-cosmetic]').forEach(b=>b.onclick=()=>equipCosmetic(b.dataset.equipCosmetic));};draw();
}
function pocketBody(tab){
 if(tab==='weapons')return `<div class="item-grid">${D.weapons.map(w=>{const owned=save.weapons.unlocked.includes(w.id),range=save.weapons.range[w.id]||1,cost=D.rangeCosts[range]||0;return `<article class="item-card ${owned?'owned':''} ${save.weapons.main===w.id?'selected':''}"><span class="item-icon">${w.icon}</span><h3>${w.name}</h3><p>${w.desc}</p><p>Reichweite: Stufe ${range}/5</p><div class="row"><button class="secondary" data-equip-weapon="${w.id}" ${!owned?'disabled':''}>${save.weapons.main===w.id?'Ausgewählt':'Ausrüsten'}</button><button class="primary" data-range="${w.id}" ${!owned||range>=5||save.wallet.books<cost?'disabled':''}>${range>=5?'Maximum':fmt(cost)+' 📚'}</button></div></article>`;}).join('')}</div>`;
 if(tab==='cosmetics')return `<div class="grid-2"><div class="avatar-preview">${avatarMarkup()}</div><div class="item-grid">${D.cosmetics.filter(c=>save.inventory.cosmetics.includes(c.id)).map(c=>`<article class="item-card"><span class="item-icon" style="color:${c.color}">◆</span><h3>${c.name}</h3><button class="secondary" data-equip-cosmetic="${c.id}">Anlegen</button></article>`).join('')}</div></div>`;
 if(tab==='items')return `<div class="item-grid"><article class="item-card"><span class="item-icon">☎</span><h3>Abholen lassen</h3><p>Sicherer Levelabbruch am letzten Snackautomaten. Nicht im Bosskampf.</p><b>${save.inventory.pickupCalls} vorhanden</b></article>${save.inventory.storyItems.map(i=>`<article class="item-card"><span class="item-icon">◇</span><h3>${esc(i)}</h3><p>Ein Erinnerungsstück aus der Schulwelt.</p></article>`).join('')||'<p class="muted">Noch keine Storygegenstände gefunden.</p>'}</div>`;
 const completed=Object.keys(save.story.completed).length;return `<div class="panel"><h2>Sammlungsfortschritt</h2><p>Story-Level: ${completed}/32</p><div class="progress"><i style="width:${completed/32*100}%"></i></div><p>Waffen: ${save.weapons.unlocked.length}/8</p><p>Kosmetik: ${save.inventory.cosmetics.length}/${D.cosmetics.length}</p><p>Erfolge: ${save.achievements.unlocked.length}/50</p></div>`;
}
function equipCosmetic(id){const c=D.cosmetics.find(x=>x.id===id);if(!c)return;if(['shirt','pants','hair'].includes(c.type)){save.inventory.selected[c.type]=id;save.profile[c.type]=c.color;}saveNow();renderPocket();}
function rangeUpgrade(id){const range=save.weapons.range[id]||1,cost=D.rangeCosts[range];if(range>=5||!S.transaction(save,`range-${id}-${range}-${Date.now()}`,'weapon_range','books',-cost,{id,range:range+1}))return;save.weapons.range[id]=range+1;saveNow();renderPocket();}

function renderShop(){
 screen.innerHTML=`<div class="page">${header('Schulkiosk','main','Keine gekaufte Spielstärke. Kosmetik und transparente Gameplay-Belohnungen.')}<div class="grid-2"><section class="panel"><h2>Schultaschen</h2><p>Werbeschultasche: ${save.loot.adBagsToday}/3 heute</p><p class="muted">55 % alt · 30 % normal · 11 % selten · 3,5 % episch · 0,5 % legendär</p><p>Garantie: episch in spätestens ${Math.max(0,30-save.loot.pity.epic)} · legendär in spätestens ${Math.max(0,100-save.loot.pity.legendary)}</p><div class="row"><button id="openOwnedBag" class="secondary">Vorhandene Tasche öffnen</button><button id="adBag" class="primary" ${save.loot.adBagsToday>=3?'disabled':''}>Rewarded-Ad-Mock</button></div></section><section class="panel"><h2>Währungen</h2><p>Optionale IAP-Mocks verwenden keine echten Storepreise.</p><button id="mockIap" class="secondary">Mock: 100 Kaugummis</button></section></div><h2 style="margin-top:24px">Kosmetik</h2><div class="item-grid">${D.cosmetics.map(c=>`<article class="item-card ${save.inventory.cosmetics.includes(c.id)?'owned':''}"><span class="item-icon" style="color:${c.color}">◆</span><h3>${c.name}</h3><p class="price">${fmt(c.price)} 📚</p><button class="primary" data-buy="${c.id}" ${save.inventory.cosmetics.includes(c.id)||save.wallet.books<c.price?'disabled':''}>${save.inventory.cosmetics.includes(c.id)?'Besitzt du':'Kaufen'}</button></article>`).join('')}</div></div>`;
 bindNav();screen.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buyCosmetic(b.dataset.buy));document.getElementById('openOwnedBag').onclick=openOwnedBag;document.getElementById('adBag').onclick=openAdBag;document.getElementById('mockIap').onclick=mockIap;
}
function buyCosmetic(id){const c=D.cosmetics.find(x=>x.id===id);if(!c||save.inventory.cosmetics.includes(id))return;showModal(`<h2>Kauf bestätigen</h2><p>${esc(c.name)} für ${fmt(c.price)} Bücher kaufen?</p><div class="modal-actions"><button class="secondary" id="cancel">Abbrechen</button><button class="primary" id="confirm">Kaufen</button></div>`);document.getElementById('cancel').onclick=closeModal;document.getElementById('confirm').onclick=()=>{if(S.transaction(save,`shop-${id}`,'shop_purchase','books',-c.price,{id})){save.inventory.cosmetics.push(id);saveNow();A.sfx('grade');}closeModal();renderShop();};}
function firstBag(){return Object.entries(save.inventory.bags).find(([,n])=>n>0);}
function openOwnedBag(){const b=firstBag();if(!b){showModal(`<h2>Keine Schultasche</h2><p>Schultaschen gibt es durch Story, tägliche Belohnungen oder freiwillige Werbe-Mocks.</p><div class="modal-actions"><button class="primary" id="ok">Okay</button></div>`);document.getElementById('ok').onclick=closeModal;return;}save.inventory.bags[b[0]]--;grantBagReward(D.lootRarities.find(r=>r.id===b[0])||D.lootRarities[0]);}
async function openAdBag(){if(save.loot.adBagsToday>=3)return;const result=await Services.ads.show('daily_bag');if(!result.completed)return;save.loot.adBagsToday++;const rarity=L.rollLoot(D.lootRarities,save.loot.pity);save.loot.pity=L.updatePity(save.loot.pity,rarity);grantBagReward(rarity,result.receipt);}
function grantBagReward(rarity,receipt=`local-${Date.now()}`){const rewards={old:[250,500],normal:[500,1000],rare:[1000,1800],epic:[2000,3500],legendary:[5000,10000]},range=rewards[rarity.id],books=range[0]+Math.floor(Math.random()*(range[1]-range[0]+1));S.transaction(save,`bag-${receipt}`,'loot_bag','books',books,{rarity:rarity.id});if(rarity.id==='epic'&&Math.random()<.25)save.inventory.pickupCalls++;if(rarity.id==='legendary'){save.inventory.pickupCalls++;save.wallet.gum+=15;}save.stats.bagsOpened++;saveNow();A.sfx('grade');showModal(`<h2 style="color:${rarity.color}">${rarity.name}</h2><div class="grade-stamp">${rarity.id==='legendary'?'★':'◆'}</div><p>Inhalt: <b>${fmt(books)} Bücher</b>${rarity.id==='legendary'?' und 15 Kaugummis':''}</p><div class="modal-actions"><button class="primary" id="ok">Einpacken</button></div>`);document.getElementById('ok').onclick=()=>{closeModal();renderShop();};}
async function mockIap(){const r=await Services.iap.purchase('gum_mock_100');if(r.success&&S.transaction(save,r.receipt,'iap_mock','gum',100,{product:r.productId})){saveNow();renderShop();}}

function renderReport(){
 let tab='grades';const draw=async()=>{const body=tab==='grades'?gradesView():tab==='achievements'?achievementsView():tab==='endless'?await endlessView():tab==='friends'?friendsView():skillsReport();screen.innerHTML=`<div class="page">${header('Zeugnis','main')}<div class="tabs"><button class="tab ${tab==='grades'?'active':''}" data-tab="grades">Meine Noten</button><button class="tab ${tab==='endless'?'active':''}" data-tab="endless">Dauernachsitzen</button><button class="tab ${tab==='achievements'?'active':''}" data-tab="achievements">Erfolge</button><button class="tab ${tab==='friends'?'active':''}" data-tab="friends">Freunde</button><button class="tab ${tab==='skills'?'active':''}" data-tab="skills">Fähigkeiten</button></div>${body}</div>`;bindNav();screen.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;draw();});const add=document.getElementById('addFriend');if(add)add.onclick=()=>{const code=document.getElementById('friendCode').value.trim();if(code)Services.friends.request(code).then(()=>draw());};};draw();
}
function gradesView(){const rows=[];D.chapters.forEach((ch,ci)=>ch.levels.forEach((lv,li)=>{const st=save.story.levelStats[`${ci+1}-${li+1}`];if(st)rows.push(`<tr><td>${ci+1}.${li+1} ${esc(lv[0])}</td><td><b>${st.grade}</b></td><td>${formatTime(st.bestTime)}</td><td>${st.deaths||0}</td><td>${st.doodles||0}/3</td><td>${st.hospitalUses||0}</td></tr>`);}));return `<div class="panel"><table class="report-table"><thead><tr><th>Level</th><th>Note</th><th>Zeit</th><th>Tode</th><th>Kritzeleien</th><th>Krankenzimmer</th></tr></thead><tbody>${rows.join('')||'<tr><td colspan="6">Noch keine abgeschlossenen Level.</td></tr>'}</tbody></table></div>`;}
function achievementsView(){return `<div class="panel">${D.achievements.map((a,i)=>{const unlocked=save.achievements.unlocked.includes(a.id)||i<Object.keys(save.story.completed).length;return `<div class="achievement ${unlocked?'':'locked'}"><span class="item-icon">${unlocked?'✓':'□'}</span><div><b>${a.name}</b><p class="muted">${a.desc}</p></div></div>`;}).join('')}</div>`;}
async function endlessView(){const rows=await Services.leaderboards.get();return `<div class="grid-2"><div class="panel"><h2>Eigene Bestleistung</h2><div class="grade-stamp">${fmt(save.endless.bestScore)}</div><p>Distanz: ${fmt(save.endless.bestDistance)} m</p></div><div class="panel"><h2>Lokale Ranglistenansicht</h2>${rows.map((r,i)=>`<div class="row spread"><span>${i+1}. ${esc(r.name)}</span><b>${fmt(r.score)} · ${r.revives} Revives</b></div>`).join('')||'<p class="muted">Noch keine verifizierbaren lokalen Läufe.</p>'}</div></div>`;}
function friendsView(){return `<div class="grid-2"><div class="panel"><h2>Dein Freundescode</h2><div class="grade-stamp">${save.profile.friendCode}</div><p>Kein freier Chat. Profile enthalten keine Kontaktangaben.</p></div><div class="panel"><h2>Freund hinzufügen</h2><div class="row"><input id="friendCode" maxlength="9" placeholder="ABCD-EFGH"><button id="addFriend" class="primary">Anfrage</button></div></div></div>`;}
function skillsReport(){return `<div class="item-grid">${D.abilities.map(a=>`<div class="item-card"><span class="item-icon">${a.icon}</span><h3>${a.name}</h3><p>Stufe ${save.abilities[a.id]||0}/${a.max}</p></div>`).join('')}</div>`;}

function renderSettings(){screen.innerHTML=`<div class="page">${header('Einstellungen','main')}<div class="panel stack">${slider('music','Musik',0,1,.05)}${slider('sfx','Soundeffekte',0,1,.05)}${slider('touchScale','Touchbutton-Größe',.75,1.4,.05)}${slider('touchOpacity','Touchbutton-Transparenz',.3,1,.05)}${slider('aimAssist','Zielhilfe',0,1,.1)}${toggle('screenShake','Screen Shake')}${toggle('reducedMotion','Reduzierte Bewegung')}${toggle('reducedFlashes','Reduzierte Blitze')}${toggle('batterySaver','Battery Saver (30 FPS)')}${toggle('consentAds','Einwilligung für freiwillige Ads')}${toggle('consentAnalytics','Einwilligung für Analytics')}<div class="row"><button id="restorePurchases" class="secondary">Käufe wiederherstellen</button><button id="resetControls" class="secondary">Steuerung zurücksetzen</button><button id="resetSave" class="danger">Spielstand löschen</button></div><p class="muted">Datenschutztexte und Storekonfigurationen sind Vorlagen und müssen vor Veröffentlichung rechtlich geprüft werden.</p></div></div>`;bindNav();screen.querySelectorAll('[data-setting]').forEach(el=>{el.addEventListener('input',()=>{save.settings[el.dataset.setting]=el.type==='checkbox'?el.checked:Number(el.value);applySettings();saveNow();});});document.getElementById('restorePurchases').onclick=()=>Services.iap.restore().then(()=>toast('Mock-Wiederherstellung abgeschlossen.'));document.getElementById('resetControls').onclick=()=>{save.settings.touchScale=1;save.settings.touchOpacity=.78;saveNow();renderSettings();};document.getElementById('resetSave').onclick=()=>showModal(`<h2>Spielstand löschen?</h2><p>Lokaler Fortschritt, Währungen und Einstellungen werden zurückgesetzt.</p><div class="modal-actions"><button class="secondary" id="cancel">Abbrechen</button><button class="danger" id="confirm">Endgültig löschen</button></div>`);setTimeout(()=>{const c=document.getElementById('cancel'),x=document.getElementById('confirm');if(c)c.onclick=closeModal;if(x)x.onclick=()=>{save=S.reset();closeModal();navigate('main');};},0);applySettings();}
function slider(id,label,min,max,step){return `<label class="setting-row"><span>${label}</span><input type="range" min="${min}" max="${max}" step="${step}" value="${save.settings[id]}" data-setting="${id}"></label>`;}
function toggle(id,label){return `<label class="setting-row"><span>${label}</span><input type="checkbox" ${save.settings[id]?'checked':''} data-setting="${id}"></label>`;}
function applySettings(){A.setVolumes(save.settings);document.documentElement.style.setProperty('--touch-scale',save.settings.touchScale);document.getElementById('touchControls').style.opacity=save.settings.touchOpacity;document.querySelectorAll('.touch-button').forEach(b=>b.style.transform=`scale(${save.settings.touchScale})`);}

function dailyClaim(){const today=new Date().toISOString().slice(0,10);if(save.daily.lastClaim===today){showModal(`<h2>Bereits abgeholt</h2><p>Die nächste Belohnung ist am nächsten Kalendertag verfügbar.</p><div class="modal-actions"><button id="ok" class="primary">Okay</button></div>`);document.getElementById('ok').onclick=closeModal;return;}const reward=D.dailyWeeks[save.daily.weekIndex%8][save.daily.streak%7];showModal(`<h2>Tägliche Belohnung</h2><div class="grade-stamp">Tag ${save.daily.streak%7+1}</div><p>${reward.label}</p><div class="modal-actions"><button id="claim" class="primary">Abholen</button></div>`);document.getElementById('claim').onclick=()=>{grantDaily(reward);save.daily.lastClaim=today;save.daily.streak++;save.daily.total++;if(save.daily.streak%7===0)save.daily.weekIndex++;if(save.daily.total%28===0)save.inventory.bags.epic=(save.inventory.bags.epic||0)+1;saveNow();closeModal();};}
function grantDaily(r){if(r.type==='books')save.wallet.books+=r.value;if(r.type==='gum')save.wallet.gum+=r.value;if(r.type==='bag')save.inventory.bags[r.value]=(save.inventory.bags[r.value]||0)+1;if(r.type==='cosmetic'&&!save.inventory.cosmetics.includes(r.value))save.inventory.cosmetics.push(r.value);}

class GameEngine{
 constructor(opts){this.opts=opts;this.mode=opts.mode;this.level=L.createLevel(opts.chapter,opts.level,this.mode==='endless'?777:undefined);if(this.mode==='phone'){this.level=L.createLevel(0,2,333);this.level.width=3800;}if(this.mode==='training'){this.level=L.createLevel(0,0,222);this.level.width=4200;this.level.enemies=this.level.enemies.slice(0,5);}this.palette=D.chapters[opts.chapter]?.palette||D.chapters[0].palette;this.camera={x:0,y:0};this.time=0;this.finished=false;this.paused=false;this.checkpoint={x:80,y:this.level.floorY-52,active:false};this.run={books:0,gum:0,doodles:0,deaths:0,heartsLost:0,hospitalUses:0,pickupUses:0,kills:0,bosses:0,revives:0,maxCombo:0};this.combo=0;this.comboTimer=0;this.lastShot=-9;this.projectiles=[];this.enemyProjectiles=[];this.particles=[];this.enemies=this.level.enemies.map((e,i)=>({...e,id:i,w:38,h:44,vx:(i%2?1:-1)*(40+opts.chapter*4),alive:true,slow:0,shield:e.type%7===2}));this.collectibles=this.level.collectibles.map((c,i)=>({...c,id:i,taken:false,bob:i*.7}));this.boss=null;this.arena=false;this.goalUnlocked=!this.level.isBoss;this.player=this.makePlayer();this.endlessOffset=0;this.endlessSpeed=120;this.shake=0;}
 makePlayer(){const hearts=this.mode==='endless'?1:3+(save.abilities.hearts||0);let x=80;const resume=save.story.checkpointResume[this.level.id];if(this.mode==='story'&&resume?.x)x=resume.x;return{x,y:this.level.floorY-52,w:30,h:48,vx:0,vy:0,grounded:false,coyote:0,jumpBuffer:0,jumps:0,dashUsed:false,facing:1,health:hearts,maxHealth:hearts,invuln:0,sprintEnergy:1,sliding:false,groundPound:false,hospitalShield:false};}
 unlocked(id){if(this.mode==='training')return true;const a=D.abilities.find(x=>x.id===id);return !a||skillUnlocked(a);}
 update(dt){if(this.paused||this.finished)return;this.time+=dt;save.stats.playSeconds+=dt;const p=this.player;if(p.invuln>0)p.invuln-=dt;if(this.mode==='endless'){this.endlessSpeed=Math.min(310,120+this.time*1.2);this.camera.x+=this.endlessSpeed*dt;if(p.x<this.camera.x+18)return this.killPlayer(true);if(p.x>this.level.width-1500)this.extendEndless();}
 const accel=p.grounded?1500:850,max=(input.sprint&&this.unlocked('sprint')&&p.sprintEnergy>0?280:185);let dir=(input.right?1:0)-(input.left?1:0);if(dir){p.vx=L.clamp(p.vx+dir*accel*dt,-max,max);p.facing=dir;p.sliding=false;}else p.vx*=Math.pow(p.grounded?.0005:.04,dt);
 if(input.sprint&&dir&&this.unlocked('sprint'))p.sprintEnergy=Math.max(0,p.sprintEnergy-dt*.24);else p.sprintEnergy=Math.min(1,p.sprintEnergy+dt*.16*(1+(save.abilities.sprint||0)*.18));
 p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);if(input.jumpPressed)p.jumpBuffer=.13;if(p.grounded){p.coyote=.11+(save.abilities.jump||0)*.015;p.jumps=0;p.dashUsed=false;}else p.coyote=Math.max(0,p.coyote-dt);
 if(p.jumpBuffer>0&&(p.coyote>0||(this.unlocked('doubleJump')&&p.jumps<2))){const double=!p.grounded&&p.coyote<=0;p.vy=double?-420-(save.abilities.doubleJump||0)*12:-455-(save.abilities.jump||0)*5;p.grounded=false;p.coyote=0;p.jumpBuffer=0;p.jumps=double?2:1;A.sfx('jump');this.burst(p.x+p.w/2,p.y+p.h,'#f2e6d0',double?10:5);}
 if(!input.jump&&p.vy<0)p.vy+=1100*dt;
 if(input.down&&p.grounded&&Math.abs(p.vx)>70&&this.unlocked('slide')){p.sliding=true;p.h=29;p.vx*=1.005;}else if(!input.down&&p.h<48){p.y-=19;p.h=48;p.sliding=false;}
 if(input.dashPressed&&this.unlocked('dash')&&!p.grounded&&!p.dashUsed){p.vx=p.facing*(470+(save.abilities.dash||0)*25);p.vy=0;p.dashUsed=true;A.sfx('dash');this.burst(p.x,p.y,'#a9e8ff',16);}
 if(input.down&&input.jumpPressed&&!p.grounded&&this.unlocked('groundPound')){p.groundPound=true;p.vy=680;}
 p.vy+=1120*dt;p.vy=Math.min(p.vy,720);const oldY=p.y;p.x+=p.vx*dt;this.collideHorizontal(p);p.y+=p.vy*dt;p.grounded=false;this.collideVertical(p,oldY);if(p.y>canvas.height+260)this.killPlayer(true);
 if(input.attackPressed&&this.time-this.lastShot>(D.weapons.find(w=>w.id===save.weapons.main)?.cooldown||.3))this.shoot();
 this.updateProjectiles(dt);this.updateEnemies(dt);this.updateCollectibles(dt);this.updateBoss(dt);this.updateCheckpoint();this.updateGoal();this.updateParticles(dt);this.comboTimer-=dt;if(this.comboTimer<=0)this.combo=Math.max(0,this.combo-dt*2);this.run.maxCombo=Math.max(this.run.maxCombo,Math.floor(this.combo));
 if(this.mode!=='endless')this.camera.x=L.clamp(L.lerp(this.camera.x,p.x-280+p.facing*70,1-Math.pow(.001,dt)),0,Math.max(0,this.level.width-canvas.width));else this.camera.x=Math.max(this.camera.x,p.x-360);
 this.camera.y=L.lerp(this.camera.y,L.clamp(p.y-300,-80,130),1-Math.pow(.01,dt));if(this.shake>0)this.shake-=dt;this.updateHud();input.jumpPressed=input.attackPressed=input.dashPressed=input.interactPressed=false;
 }
 collideHorizontal(p){for(const pl of this.level.platforms){if(rect(p,pl)&&p.y+p.h>pl.y+4){if(p.vx>0)p.x=pl.x-p.w;else if(p.vx<0)p.x=pl.x+pl.w;p.vx=0;if(this.unlocked('wallJump')&&!p.grounded&&input.jumpPressed){p.vy=-410;p.vx=(p.x<pl.x?-1:1)*300;p.facing=Math.sign(p.vx);A.sfx('jump');}}}p.x=L.clamp(p.x,0,this.level.width-p.w);}
 collideVertical(p,oldY){for(const pl of this.level.platforms){if(p.x+p.w<=pl.x+2||p.x>=pl.x+pl.w-2)continue;if(p.vy>=0&&oldY+p.h<=pl.y+10&&p.y+p.h>=pl.y){p.y=pl.y-p.h;if(p.groundPound){this.burst(p.x+p.w/2,p.y+p.h,'#f5dc8a',25);this.damageNearby(p.x,130);p.groundPound=false;this.shake=.16;}p.vy=0;p.grounded=true;}else if(p.vy<0&&oldY>=pl.y+pl.h-8&&p.y<=pl.y+pl.h){p.y=pl.y+pl.h;p.vy=20;}}}
 shoot(){const w=D.weapons.find(x=>x.id===save.weapons.main)||D.weapons[0],rangeLevel=save.weapons.range[w.id]||1;this.lastShot=this.time;let count=w.behavior==='burst'?3:1;for(let i=0;i<count;i++){this.projectiles.push({x:this.player.x+this.player.w/2,y:this.player.y+20,vx:this.player.facing*w.speed,vy:w.behavior==='burst'?(i-1)*65:0,life:(w.range*(1+(rangeLevel-1)*.15))/w.speed,damage:w.damage,pierce:w.behavior==='pierce',slow:w.behavior==='slow',splash:w.behavior==='splash',bounces:this.unlocked('bounce')?Math.min(2,save.abilities.bounce||1):0});}A.sfx('shoot');}
 updateProjectiles(dt){for(const pr of this.projectiles){pr.x+=pr.vx*dt;pr.y+=pr.vy*dt;pr.life-=dt;if(pr.y<0||pr.y>540){if(pr.bounces>0){pr.vy*=-1;pr.bounces--;}else pr.life=0;}for(const e of this.enemies){if(e.alive&&rect({x:pr.x-4,y:pr.y-4,w:8,h:8},e)){this.hitEnemy(e,pr.damage,pr);if(!pr.pierce)pr.life=0;}}if(this.boss&&this.boss.alive&&rect({x:pr.x-4,y:pr.y-4,w:8,h:8},this.boss)){this.boss.hp-=pr.damage;this.burst(pr.x,pr.y,'#fff2a8',8);if(!pr.pierce)pr.life=0;}}this.projectiles=this.projectiles.filter(p=>p.life>0);
 for(const pr of this.enemyProjectiles){pr.x+=pr.vx*dt;pr.y+=pr.vy*dt;pr.life-=dt;if(rect({x:pr.x-7,y:pr.y-7,w:14,h:14},this.player)){this.damagePlayer(pr.damage||1);pr.life=0;}}this.enemyProjectiles=this.enemyProjectiles.filter(p=>p.life>0);}
 hitEnemy(e,damage,pr){if(e.shield&&pr.damage<2){pr.vx*=-.5;A.sfx('hit');return;}e.hp-=damage;if(pr.slow)e.slow=2;if(pr.splash)this.damageNearby(e.x,90,.5);this.burst(e.x+e.w/2,e.y+20,'#f5e5c2',6);A.sfx('hit');if(e.hp<=0){e.alive=false;this.run.kills++;save.stats.enemiesDefeated++;const gain=(e.elite?14:2)+Math.floor(Math.random()*4);this.run.books+=gain;this.combo+=1;this.comboTimer=2.4;}}
 damageNearby(x,radius,damage=1){for(const e of this.enemies)if(e.alive&&Math.abs(e.x-x)<radius)this.hitEnemy(e,damage,{});}
 updateEnemies(dt){for(const e of this.enemies){if(!e.alive)continue;e.slow=Math.max(0,e.slow-dt);const mult=e.slow>0?.35:1;e.x+=e.vx*dt*mult;if(e.x<100||e.x>this.level.width-100)e.vx*=-1;if(Math.abs(e.x-this.player.x)<500&&Math.random()<dt*(.15+this.opts.chapter*.03)){const dx=this.player.x-e.x,dy=this.player.y-e.y,len=Math.hypot(dx,dy)||1;this.enemyProjectiles.push({x:e.x+20,y:e.y+15,vx:dx/len*210,vy:dy/len*210,life:3,damage:1});}if(rect(this.player,e))this.damagePlayer(e.elite?2:1);}}
 updateCollectibles(dt){for(const c of this.collectibles){if(c.taken)continue;c.bob+=dt*3;const box={x:c.x,y:c.y+Math.sin(c.bob)*5,w:22,h:22};if(rect(this.player,box)){c.taken=true;if(c.kind==='book')this.run.books+=c.value;if(c.kind==='gum')this.run.gum+=1;if(c.kind==='doodle')this.run.doodles++;A.sfx('collect');this.burst(c.x,c.y,c.kind==='gum'?'#ef7fa5':'#ffe58e',8);}}}
 updateCheckpoint(){if(!this.checkpoint.active&&this.player.x>this.level.checkpointX-25){this.checkpoint={x:this.level.checkpointX,y:this.level.floorY-60,active:true};if(this.mode==='story'){save.story.checkpointResume[this.level.id]={x:this.level.checkpointX-60};saveNow();}A.sfx('checkpoint');toast('Snackautomat aktiviert – Fortschritt gespeichert');}}
 updateBoss(dt){if(!this.level.isBoss||this.mode==='training'||this.mode==='phone')return;if(!this.arena&&this.player.x>this.level.goalX-1050){this.arena=true;this.boss={x:this.level.goalX-420,y:this.level.floorY-128,w:96,h:128,hp:24+this.opts.chapter*8,maxHp:24+this.opts.chapter*8,alive:true,phase:1,t:0,name:D.chapters[this.opts.chapter].boss};refs.bossHud.classList.remove('hidden');refs.bossName.textContent=this.boss.name;A.startMusic('boss');A.sfx('boss');toast(`Boss: ${this.boss.name}`,2400);}const b=this.boss;if(!b||!b.alive)return;b.t+=dt;b.phase=b.hp<b.maxHp*.33?3:b.hp<b.maxHp*.66?2:1;b.x+=Math.sin(this.time*(1+b.phase*.22))*35*dt;if(b.t>Math.max(.55,1.55-b.phase*.22)){b.t=0;const dx=this.player.x-b.x,dy=this.player.y-b.y,len=Math.hypot(dx,dy)||1;for(let i=0;i<b.phase;i++){const angle=(i-(b.phase-1)/2)*.22,cs=Math.cos(angle),sn=Math.sin(angle),vx=dx/len*250,vy=dy/len*250;this.enemyProjectiles.push({x:b.x+20,y:b.y+30,vx:vx*cs-vy*sn,vy:vx*sn+vy*cs,life:4,damage:b.phase===3&&i===1?2:1});}}if(rect(this.player,b))this.damagePlayer(b.phase===3?2:1);refs.bossBar.style.width=`${Math.max(0,b.hp/b.maxHp*100)}%`;if(b.hp<=0){b.alive=false;this.goalUnlocked=true;this.run.bosses++;this.run.books+=this.opts.chapter===7?1000:150+this.opts.chapter*100;refs.bossHud.classList.add('hidden');this.burst(b.x+40,b.y+50,'#f6d16e',50);A.startMusic('game');toast('Boss besiegt – Ausgang geöffnet',2500);}}
 updateGoal(){if(this.goalUnlocked&&this.player.x>this.level.goalX&&this.player.grounded){this.complete();}}
 damagePlayer(amount){const p=this.player;if(p.invuln>0||this.finished)return;if(p.hospitalShield){p.hospitalShield=false;p.invuln=.6;toast('Krankenzimmer-Schild blockiert den Treffer');return;}p.health-=amount;p.invuln=1.2+(save.abilities.invuln||0)*.2;this.run.heartsLost+=amount;this.shake=.16;A.sfx('hurt');if(p.health<=0)this.killPlayer(false);}
 killPlayer(fall){this.run.deaths++;save.stats.deaths++;if(this.mode==='endless'){this.endlessGameOver();return;}this.player.x=this.checkpoint.active?this.checkpoint.x:80;this.player.y=this.level.floorY-52;this.player.vx=this.player.vy=0;this.player.health=this.player.maxHealth;this.player.invuln=1.2;this.burst(this.player.x,this.player.y,'#ddd',16);toast(fall?'Abgrund – zurück zum Snackautomaten':'Zurück zum Snackautomaten');}
 complete(){if(this.finished)return;this.finished=true;const stats={time:this.time,targetTime:this.level.targetTime,deaths:this.run.deaths,heartsLost:this.run.heartsLost,doodles:this.run.doodles,gum:this.run.gum,maxGum:5,books:this.run.books,targetBooks:this.level.targetBooks,hospitalUses:this.run.hospitalUses,pickupUses:this.run.pickupUses,optional:this.run.doodles===3};const grade=L.gradeLevel(stats);A.sfx('grade');if(this.mode==='story')this.applyStoryRewards(grade,stats);showModal(`<div class="row spread"><div><h2>Level abgeschlossen</h2><p>${D.chapters[this.opts.chapter].levels[this.opts.level][0]}</p></div><span class="grade-stamp">${grade}</span></div><div class="grid-3"><div><b>${formatTime(this.time)}</b><p class="muted">Zeit</p></div><div><b>${this.run.doodles}/3</b><p class="muted">Kritzeleien</p></div><div><b>${fmt(this.run.books)} 📚 · ${this.run.gum} ●</b><p class="muted">Belohnung</p></div></div><div class="modal-actions"><button class="secondary" id="doubleReward">Rewarded-Ad-Mock: verdoppeln</button><button class="primary" id="continue">Weiter</button></div>`);document.getElementById('continue').onclick=()=>{closeModal();navigate('story');};document.getElementById('doubleReward').onclick=async()=>{const r=await Services.ads.show('level_double');if(r.completed&&S.transaction(save,`double-${this.level.id}-${r.receipt}`,'rewarded_double','books',this.run.books,{level:this.level.id})){save.wallet.gum+=this.run.gum;saveNow();document.getElementById('doubleReward').disabled=true;document.getElementById('doubleReward').textContent='Belohnung verdoppelt';}};}
 applyStoryRewards(grade,stats){const id=this.level.id,first=!save.story.completed[id];save.story.completed[id]=true;save.story.unlocked=Math.max(save.story.unlocked,Math.min(32,this.level.global+1));const old=save.story.levelStats[id]||{};save.story.levelStats[id]={grade:L.betterGrade(old.grade,grade),bestTime:old.bestTime?Math.min(old.bestTime,this.time):this.time,deaths:Math.min(old.deaths??999,stats.deaths),doodles:Math.max(old.doodles||0,this.run.doodles),gum:Math.max(old.gum||0,this.run.gum),books:Math.max(old.books||0,this.run.books),hospitalUses:stats.hospitalUses};save.wallet.books+=this.run.books;save.wallet.gum+=this.run.gum;if(first){save.wallet.abilityPoints+=1+(this.level.isBoss?2:0)+(this.run.doodles===3?1:0);}for(const w of D.weapons)if(w.unlock<=this.level.global&&!save.weapons.unlocked.includes(w.id)){save.weapons.unlocked.push(w.id);save.weapons.range[w.id]=1;}if(this.level.isBoss&&this.opts.chapter===0)save.inventory.storyItems.push('Pünktlichkeitsmodul');if(this.level.global===32){save.wallet.gum+=25;save.inventory.cosmetics.push('skin_schoolout');save.inventory.bags.legendary=(save.inventory.bags.legendary||0)+1;}delete save.story.checkpointResume[id];saveNow();Services.analytics.event('level_completed',{id,grade,time:Math.round(this.time)});}
 extendEndless(){const old=this.level.width;this.level.width+=7000;this.level.platforms[0].w=this.level.width;const extra=L.createLevel(7,3,Math.floor(this.time*1000));for(const p of extra.platforms.slice(1))this.level.platforms.push({...p,x:p.x+old-200});for(const e of extra.enemies)this.enemies.push({...e,x:e.x+old-200,w:38,h:44,vx:Math.random()<.5?-90:90,alive:true,slow:0,shield:false});for(const c of extra.collectibles)this.collectibles.push({...c,x:c.x+old-200,taken:false,bob:Math.random()*5});}
 endlessGameOver(){if(this.finished)return;this.finished=true;const distance=Math.max(0,Math.floor((this.player.x-80)/10)),score=L.scoreEndless({distance,time:this.time,kills:this.run.kills,bosses:this.run.bosses,books:this.run.books,maxCombo:this.run.maxCombo,noHit:this.run.revives===0});save.endless.bestScore=Math.max(save.endless.bestScore,score);save.endless.bestDistance=Math.max(save.endless.bestDistance,distance);const result={name:save.profile.name,score,distance,revives:this.run.revives,at:Date.now()};save.endless.runs.unshift(result);save.endless.runs=save.endless.runs.slice(0,20);saveNow();Services.leaderboards.submit(result);showModal(`<h2>Dauernachsitzen beendet</h2><div class="grade-stamp">${fmt(score)}</div><p>${fmt(distance)} m · ${this.run.kills} Gegner · ${this.run.revives} Wiederbelebungen</p><div class="modal-actions"><button id="revive" class="secondary">Rewarded-Ad-Mock wiederbeleben</button><button id="end" class="primary">Zum Zeugnis</button></div>`);document.getElementById('end').onclick=()=>{closeModal();navigate('report');};document.getElementById('revive').onclick=async()=>{const r=await Services.ads.show('endless_revive');if(r.completed){closeModal();this.finished=false;this.run.revives++;this.player.health=1;this.player.x=this.camera.x+320;this.player.y=this.level.floorY-52;this.player.invuln=2;}};}
 updateParticles(dt){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=350*dt;p.life-=dt;}this.particles=this.particles.filter(p=>p.life>0);}
 burst(x,y,color,count){for(let i=0;i<count;i++)this.particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.8)*240,life:.35+Math.random()*.45,color});}
 updateHud(){refs.hearts.textContent='♥'.repeat(Math.max(0,this.player.health))+'♡'.repeat(Math.max(0,this.player.maxHealth-this.player.health));refs.runBooks.textContent=fmt(this.run.books);refs.runGum.textContent=this.run.gum;refs.runDoodles.textContent=this.run.doodles;}
 draw(){const shakeX=this.shake>0&&save.settings.screenShake?(Math.random()-.5)*8:0,camX=this.camera.x+shakeX,camY=this.camera.y;this.drawBackground(camX,camY);ctx.save();ctx.translate(-camX,-camY);this.drawWorld();ctx.restore();if(this.mode==='endless'){ctx.fillStyle='#fff';ctx.font='bold 18px monospace';ctx.fillText(`${Math.max(0,Math.floor((this.player.x-80)/10))} m`,20,90);}if(this.mode==='training'){ctx.fillStyle='#07101fcc';ctx.fillRect(280,14,400,40);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 18px sans-serif';ctx.fillText(`Training${this.opts.focus?' · '+(D.abilities.find(a=>a.id===this.opts.focus)?.name||''):''} – Abgründe setzen sofort zurück`,480,41);ctx.textAlign='left';}}
 drawBackground(camX,camY){const [sky,far,near,ground]=this.palette;ctx.fillStyle=sky;ctx.fillRect(0,0,canvas.width,canvas.height);const t=camX*.08;ctx.fillStyle=far;for(let i=-1;i<10;i++){const x=i*150-(t%150);ctx.fillRect(x,170+(i%3)*25,125,240);ctx.fillStyle=near;for(let w=0;w<3;w++)ctx.fillRect(x+18+w*35,210,16,26);ctx.fillStyle=far;}ctx.fillStyle=near;const t2=camX*.22;for(let i=-1;i<12;i++){const x=i*100-(t2%100);ctx.fillRect(x,315+(i%2)*20,82,140);}ctx.fillStyle=ground;ctx.fillRect(0,440,canvas.width,100);}
 drawWorld(){for(const pl of this.level.platforms){ctx.fillStyle=pl.type==='breakable'?'#a66d4f':'#3e4e61';ctx.fillRect(pl.x,pl.y,pl.w,pl.h);ctx.fillStyle='#d3b96f';ctx.fillRect(pl.x,pl.y,pl.w,8);for(let x=pl.x;x<pl.x+pl.w;x+=32){ctx.strokeStyle='#263241';ctx.strokeRect(x,pl.y,32,pl.h);}}this.drawCheckpoint();for(const c of this.collectibles)if(!c.taken)this.drawCollectible(c);for(const e of this.enemies)if(e.alive)this.drawEnemy(e);if(this.boss?.alive)this.drawBoss(this.boss);for(const p of this.projectiles){ctx.fillStyle='#f5f0df';ctx.fillRect(p.x-5,p.y-5,10,10);ctx.strokeStyle='#6b7280';ctx.strokeRect(p.x-5,p.y-5,10,10);}for(const p of this.enemyProjectiles){ctx.fillStyle='#ff5874';ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();}for(const p of this.particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5);}ctx.globalAlpha=1;this.drawGoal();this.drawPlayer(this.player);}
 drawCheckpoint(){const x=this.level.checkpointX,y=this.level.floorY-70;ctx.fillStyle=this.checkpoint.active?'#c64151':'#14181e';ctx.fillRect(x,y,44,70);ctx.fillStyle='#080b10';ctx.fillRect(x+7,y+8,30,21);ctx.fillStyle=this.checkpoint.active?'#f7d762':'#323843';ctx.fillRect(x+10,y+12,24,12);ctx.fillStyle='#ddd';ctx.fillRect(x+9,y+43,10,14);ctx.fillRect(x+25,y+43,10,14);}
 drawCollectible(c){const y=c.y+Math.sin(c.bob)*5;if(c.kind==='book'){ctx.fillStyle='#f3cf58';ctx.fillRect(c.x,y,20,16);ctx.fillStyle='#8f5e35';ctx.fillRect(c.x+3,y+3,14,2);}else if(c.kind==='gum'){ctx.fillStyle='#f277a4';ctx.beginPath();ctx.arc(c.x+10,y+10,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#742c54';ctx.stroke();}else{ctx.fillStyle='#f4f0d9';ctx.fillRect(c.x,y,24,19);ctx.strokeStyle='#466c9a';ctx.strokeRect(c.x,y,24,19);ctx.fillStyle='#c1475b';ctx.fillRect(c.x+5,y+8,14,3);}}
 drawEnemy(e){ctx.save();if(e.slow>0)ctx.globalAlpha=.7;ctx.fillStyle=e.elite?'#f0a33e':'#574562';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#ddb08a';ctx.fillRect(e.x+7,e.y-10,e.w-14,21);ctx.fillStyle='#111';ctx.fillRect(e.x+10,e.y-3,5,5);ctx.fillRect(e.x+e.w-15,e.y-3,5,5);if(e.shield){ctx.strokeStyle='#9dd8ef';ctx.lineWidth=5;ctx.strokeRect(e.x-5,e.y-5,e.w+10,e.h+10);}ctx.restore();}
 drawBoss(b){ctx.fillStyle='#702c47';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#e0aa82';ctx.fillRect(b.x+18,b.y-20,b.w-36,45);ctx.fillStyle='#151515';ctx.fillRect(b.x+27,b.y-6,9,7);ctx.fillRect(b.x+b.w-36,b.y-6,9,7);ctx.fillStyle='#f1c84a';ctx.fillRect(b.x-20,b.y+30,25,70);ctx.fillRect(b.x+b.w-5,b.y+30,25,70);}
 drawGoal(){const x=this.level.goalX,y=this.level.floorY-100;ctx.fillStyle=this.goalUnlocked?'#2d7a55':'#722f43';ctx.fillRect(x,y,70,100);ctx.fillStyle='#0e1820';ctx.fillRect(x+12,y+18,46,82);ctx.fillStyle='#ffd766';ctx.fillRect(x+53,y+55,7,7);if(!this.goalUnlocked){ctx.fillStyle='#fff';ctx.font='bold 16px sans-serif';ctx.fillText('GESPERRT',x-5,y-10);}}
 drawPlayer(p){ctx.save();if(p.invuln>0&&Math.floor(p.invuln*12)%2===0)ctx.globalAlpha=.3;const x=Math.round(p.x),y=Math.round(p.y);ctx.fillStyle=save.profile.pants;ctx.fillRect(x+4,y+p.h-18,9,18);ctx.fillRect(x+p.w-13,y+p.h-18,9,18);ctx.fillStyle=save.profile.shirt;ctx.fillRect(x+2,y+17,p.w-4,p.h-30);ctx.fillStyle=save.profile.skin;ctx.fillRect(x+6,y,18,20);ctx.fillStyle=save.profile.hair;ctx.fillRect(x+4,y-3,22,8);ctx.fillStyle='#111';ctx.fillRect(x+(p.facing>0?19:9),y+8,3,3);if(p.sliding){ctx.fillStyle='#fff8';ctx.fillRect(x-15,y+p.h-4,16,3);}ctx.restore();}
}

function rect(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function startGame(opts){stopGame();currentScreen='game';setTopbar(false);screen.innerHTML='';screen.className='screen hidden';gameLayer.classList.remove('hidden');closeModal();A.resume();A.setVolumes(save.settings);A.startMusic(opts.mode==='endless'?'endless':'game');engine=new GameEngine(opts);applySettings();lastTime=performance.now();const frame=(now)=>{if(!engine)return;const maxDt=save.settings.batterySaver?1/30:1/60;let dt=Math.min(.033,(now-lastTime)/1000);lastTime=now;if(save.settings.batterySaver&&now-(frame.last||0)<33){raf=requestAnimationFrame(frame);return;}frame.last=now;engine.update(Math.max(maxDt*.5,dt));engine.draw();raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);}
function pauseGame(){if(!engine||engine.finished)return;engine.paused=true;showModal(`<h2>Pause</h2><div class="stack"><button id="resume" class="primary">Weiterspielen</button><button id="restart" class="secondary">Level neu starten</button><button id="hospital" class="secondary" ${engine.boss?.alive||save.wallet.gum<20?'disabled':''}>Krankenzimmer rufen – 20 Kaugummis</button><button id="viewPocket" class="secondary">Hosentasche ansehen</button><button id="pickup" class="secondary" ${engine.boss?.alive||save.inventory.pickupCalls<1||engine.mode!=='story'?'disabled':''}>Abholen lassen (${save.inventory.pickupCalls})</button><button id="leave" class="danger">Level verlassen</button></div>`);document.getElementById('resume').onclick=()=>{closeModal();engine.paused=false;};document.getElementById('restart').onclick=()=>{const o=engine.opts;closeModal();startGame(o);};document.getElementById('hospital').onclick=useHospital;document.getElementById('viewPocket').onclick=()=>{showModal(`<h2>Hosentasche im Level</h2><p>Hauptwaffe: <b>${D.weapons.find(w=>w.id===save.weapons.main)?.name}</b></p><p>Abholen lassen: ${save.inventory.pickupCalls}</p><p class="muted">Ausrüstung kann während eines Levels nicht geändert werden.</p><div class="modal-actions"><button class="primary" id="backPause">Zurück</button></div>`);document.getElementById('backPause').onclick=pauseGame;};document.getElementById('pickup').onclick=usePickup;document.getElementById('leave').onclick=()=>{closeModal();navigate(engine.mode==='endless'?'report':'story');};}
function useHospital(){if(!engine||save.wallet.gum<20||engine.boss?.alive)return;S.transaction(save,`hospital-${Date.now()}`,'hospital','gum',-20,{level:engine.level.id});engine.run.hospitalUses++;save.stats.hospitalUses++;engine.player.health=engine.player.maxHealth;engine.player.hospitalShield=(save.abilities.hospitalShield||0)>0;A.startMusic('hospital');showModal(`<h2>Krankenzimmer</h2><div class="grade-stamp">✚</div><p>Alle Herzen wurden aufgefüllt. Negative Effekte sind entfernt.</p><p>Krankenschwester: „Geht es dir wieder gut?“</p><div class="modal-actions"><button id="return" class="primary">Ja, zurück ins Level</button></div>`);document.getElementById('return').onclick=()=>{closeModal();engine.paused=false;A.startMusic('game');saveNow();};}
function usePickup(){if(!engine||save.inventory.pickupCalls<1||engine.boss?.alive||engine.mode!=='story')return;save.inventory.pickupCalls--;engine.run.pickupUses++;save.stats.pickupUses++;save.story.checkpointResume[engine.level.id]={x:engine.checkpoint.active?engine.checkpoint.x:80};saveNow();closeModal();navigate('story');}
function formatTime(seconds){const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return `${m}:${String(s).padStart(2,'0')}`;}

const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowDown:'down',KeyS:'down',Space:'jump',ShiftLeft:'sprint',ShiftRight:'sprint',KeyJ:'attack',KeyK:'dash',KeyE:'interact'};
window.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();if(engine&&!modalRoot.classList.contains('hidden')){closeModal();engine.paused=false;}else if(engine)pauseGame();return;}const k=keyMap[e.code];if(k){e.preventDefault();if(!input[k]){if(k==='jump')input.jumpPressed=true;if(k==='attack')input.attackPressed=true;if(k==='dash')input.dashPressed=true;if(k==='interact')input.interactPressed=true;}input[k]=true;A.resume();}});
window.addEventListener('keyup',e=>{const k=keyMap[e.code];if(k)input[k]=false;});
document.querySelectorAll('.touch-button[data-action]').forEach(btn=>{const k=btn.dataset.action;const down=e=>{e.preventDefault();btn.classList.add('active');if(!input[k]){if(k==='jump')input.jumpPressed=true;if(k==='attack')input.attackPressed=true;if(k==='dash')input.dashPressed=true;if(k==='interact')input.interactPressed=true;}input[k]=true;A.resume();};const up=e=>{e.preventDefault();btn.classList.remove('active');input[k]=false;};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('pointerleave',up);});
document.getElementById('pauseButton').addEventListener('click',pauseGame);document.getElementById('dailyButton').addEventListener('click',dailyClaim);document.getElementById('profileButton').addEventListener('click',()=>navigate('character'));
window.addEventListener('beforeunload',()=>saveNow());
function resetDailyCounter(){const today=new Date().toISOString().slice(0,10);if(save.loot.adBagDate!==today){save.loot.adBagDate=today;save.loot.adBagsToday=0;saveNow();}}
resetDailyCounter();applySettings();updateTopbar();navigate(save.profileCreated?'main':'main');
})();
